#!/bin/bash

# . "$(dirname -- "$0")/_/husky.sh"

# Obtém o nome da branch atual
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Verifica se há um merge em andamento
MERGE_HEAD_FILE="$(git rev-parse --git-dir)/MERGE_HEAD"

# Define as branches protegidas
if [ "$BRANCH" = "main" ]; then
  if [ ! -f "$MERGE_HEAD_FILE" ]; then
    echo "🚫 ERRO: Commit direto na branch '$BRANCH' não é permitido!"
    echo "💡 Crie uma branch (ex: git checkout -b feature/nova-funcionalidade) e depois faça o merge para a branch main."
    exit 1
  fi
fi

# Se não for main, ou se for um merge, o commit segue normalmente
exit 0